version: "3"
services:
  configuration_server:
    image: localhost:5000/configuration_server:latest
    ports:
      - "8888:8888"
    networks:
      bitnet:
        ipv4_address: 172.18.0.4
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      bitnet:
       ipv4_address: 172.18.0.2
    volumes:
      - mongodb_data_volume:/data/db
  bitcoind_adapter:
    image: localhost:5000/bitcoind_adapter:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      bitnet:
       ipv4_address: 172.18.0.3
    restart: on-failure
    depends_on:
      - mongo
      - configuration_server
networks:
  bitnet:
    driver: bridge
    ipam:
      config:
        - subnet:  172.18.0.0/16
#        - gateway: 172.18.0.1
volumes:
  mongodb_data_volume: